networks:
  traefik-net:
    external: true

services:
  web:
    networks:
    - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
{% for host in hosts %}
      # ------------------------------------------------------------------------
{%- if host['redirect'] %}
      # ${host['name']} -> ${host['redirect']}
{%- else %}
      # ${host['name']}
{%- endif %}
      # ------------------------------------------------------------------------
{%- set ip_whitelist_middleware = "ip-whitelist-{},".format(host['id']) if host['ip_whitelist'] else "" %}
{% if not host['redirect'] %}
{%- if host['ip_whitelist'] %}
      # ip whitelist middleware for ${host['name']}
      - "traefik.http.middlewares.ip-whitelist-${host['id']}.ipallowlist.sourcerange=${host['ip_whitelist']}"
{% endif %}
      # router - /mail/attachment/upload - 2GB
      - "traefik.http.routers.odoo-mail-upload-https-${host['id']}.rule=Host(`${host['name']}`) && PathPrefix(`/mail/attachment/upload`)"
      - "traefik.http.routers.odoo-mail-upload-https-${host['id']}.entrypoints=websecure"
      - "traefik.http.routers.odoo-mail-upload-https-${host['id']}.service=odoo-${branch_id}"
      - "traefik.http.routers.odoo-mail-upload-https-${host['id']}.tls.certresolver=${host['resolver'] or 'tls-resolver'}"
      - "traefik.http.routers.odoo-mail-upload-https-${host['id']}.middlewares=${ip_whitelist_middleware}gzip,sslheader,hsts,mem-limit,limit-2gb"
      - "traefik.http.routers.odoo-mail-upload-https-${host['id']}.priority=110"

      # router - /web/database/* - restricted
      - "traefik.http.routers.odoo-db-blocked-https-${host['id']}.rule=Host(`${host['name']}`) && PathPrefix(`/web/database/`)"
      - "traefik.http.routers.odoo-db-blocked-https-${host['id']}.entrypoints=websecure"
      - "traefik.http.routers.odoo-db-blocked-https-${host['id']}.tls=true"
      - "traefik.http.routers.odoo-db-blocked-https-${host['id']}.service=odoo-${branch_id}"
      - "traefik.http.routers.odoo-db-blocked-https-${host['id']}.middlewares=incloud-ip-whitelist@docker,gzip,sslheader,hsts,mem-limit,limit"
      - "traefik.http.routers.odoo-db-blocked-https-${host['id']}.priority=105"

      # router - /web/database/restore - unlimited
      - "traefik.http.routers.odoo-db-restore-https-${host['id']}.rule=Host(`${host['name']}`) && PathPrefix(`/web/database/restore`)"
      - "traefik.http.routers.odoo-db-restore-https-${host['id']}.entrypoints=websecure"
      - "traefik.http.routers.odoo-db-restore-https-${host['id']}.service=odoo-${branch_id}"
      - "traefik.http.routers.odoo-db-restore-https-${host['id']}.tls.certresolver=${host['resolver'] or 'tls-resolver'}"
      - "traefik.http.routers.odoo-db-restore-https-${host['id']}.middlewares=${ip_whitelist_middleware}gzip,sslheader,hsts,mem-limit,limit-unlimited"
      - "traefik.http.routers.odoo-db-restore-https-${host['id']}.priority=106"

      # router - /documents/upload - 5GB
      - "traefik.http.routers.odoo-docs-upload-https-${host['id']}.rule=Host(`${host['name']}`) && PathPrefix(`/documents/upload`)"
      - "traefik.http.routers.odoo-docs-upload-https-${host['id']}.entrypoints=websecure"
      - "traefik.http.routers.odoo-docs-upload-https-${host['id']}.service=odoo-${branch_id}"
      - "traefik.http.routers.odoo-docs-upload-https-${host['id']}.tls.certresolver=${host['resolver'] or 'tls-resolver'}"
      - "traefik.http.routers.odoo-docs-upload-https-${host['id']}.middlewares=${ip_whitelist_middleware}gzip,sslheader,hsts,mem-limit,limit-5gb"
      - "traefik.http.routers.odoo-docs-upload-https-${host['id']}.priority=100"

      # router - websocket
      - "traefik.http.routers.odoo-im-https-${host['id']}.rule=Host(`${host['name']}`) && PathPrefix(`/websocket`)"
      - "traefik.http.routers.odoo-im-https-${host['id']}.entrypoints=websecure"
      - "traefik.http.routers.odoo-im-https-${host['id']}.service=odoo-im-${branch_id}"
      - "traefik.http.routers.odoo-im-https-${host['id']}.tls.certresolver=${host['resolver'] or 'tls-resolver'}"
      - "traefik.http.routers.odoo-im-https-${host['id']}.middlewares=${ip_whitelist_middleware}gzip,sslheader,hsts,mem-limit,limit"
      - "traefik.http.routers.odoo-im-https-${host['id']}.priority=75"

      # router - main
      - "traefik.http.routers.odoo-https-${host['id']}.rule=Host(`${host['name']}`)"
      - "traefik.http.routers.odoo-https-${host['id']}.entrypoints=websecure"
      - "traefik.http.routers.odoo-https-${host['id']}.service=odoo-${branch_id}"
      - "traefik.http.routers.odoo-https-${host['id']}.tls.certresolver=${host['resolver'] or 'tls-resolver'}"
      - "traefik.http.routers.odoo-https-${host['id']}.middlewares=${ip_whitelist_middleware}gzip,sslheader,hsts,mem-limit,limit"
      - "traefik.http.routers.odoo-https-${host['id']}.priority=50"
{%- else %}
      # redirection
      - "traefik.http.routers.odoo-redirect-https-${host['id']}.rule=Host(`${host['name']}`)"
      - "traefik.http.routers.odoo-redirect-https-${host['id']}.entrypoints=websecure"
      - "traefik.http.routers.odoo-redirect-https-${host['id']}.service=odoo-${branch_id}"
      - "traefik.http.routers.odoo-redirect-https-${host['id']}.tls.certresolver=${host['resolver'] or 'tls-resolver'}"
      - "traefik.http.routers.odoo-redirect-https-${host['id']}.middlewares=${host['redirect_middleware']}"
      - "traefik.http.routers.odoo-redirect-https-${host['id']}.priority=200"

      # redirect middleware
      - "traefik.http.middlewares.${host['redirect_middleware']}.redirectregex.regex=^https?://${host['name']}(.*)"
      - "traefik.http.middlewares.${host['redirect_middleware']}.redirectregex.replacement=https://${host['redirect']}$${1}"
      - "traefik.http.middlewares.${host['redirect_middleware']}.redirectregex.permanent=true"
{%- endif %}
{% endfor %}
      # ------------------------------------------------------------------------
      # Other traefik configurations
      # ------------------------------------------------------------------------

      # services
      - "traefik.http.services.odoo-${branch_id}.loadbalancer.server.port=8069"
      - "traefik.http.services.odoo-im-${branch_id}.loadbalancer.server.port=8072"

      # various middlewares
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.hsts.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hsts.headers.stsPreload=true"
      - "traefik.http.middlewares.hsts.headers.forceSTSHeader=true"


      # body size limit middlewares
      - "traefik.http.middlewares.mem-limit.buffering.memRequestBodyBytes=20971520"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=157286400"
      - "traefik.http.middlewares.limit-2gb.buffering.maxRequestBodyBytes=2147483648"
      - "traefik.http.middlewares.limit-5gb.buffering.maxRequestBodyBytes=5368709120"
      - "traefik.http.middlewares.limit-unlimited.buffering.maxRequestBodyBytes=0"
