#!/usr/bin/env python3
import os


def execute_pg_activity():
    cmd = [
        'docker-compose',
        'exec',
        '-u odoo',
        'web',
        'pg_activity'
    ]
    os.system(' '.join(cmd))


if __name__ == "__main__":
    execute_pg_activity()
