#!/usr/bin/env python3
import os


def execute_psql():
    cmd = [
        'docker-compose',
        'exec',
        'db',
        'psql',
        '-U odoo',
        '-d postgres'
    ]
    os.system(' '.join(cmd))


if __name__ == "__main__":
    execute_psql()
