[options]

# BASE ODOO
data_dir = /var/lib/odoo
admin_passwd = ${password('odoo')}
csv_internal_sep = ,
db_maxconn = 64
unaccent = True

# SECURITY
list_db = True

# PERFORMANCE
limit_request = 8192
limit_time_cpu = 3600
limit_time_real = 7200
limit_time_real_cron = 0
max_cron_threads = 1

# SERVER
server_wide_modules = base,web
geoip_city_db = /home/odoo/geoip/GeoLite2-City.mmdb
geoip_country_db = /home/odoo/geoip/GeoLite2-Country.mmdb

# HTTP
proxy_mode = True
http_interface = 0.0.0.0

# QUEUE JOB
[queue_job]
channels = root:1